application/models.py
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import UserMixin

from application import db, manager



class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    login = db.Column(db.String(128), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False)

    def __init__(self, **kwargs):
        self.login = kwargs.get('login')
        self.password = generate_password_hash(kwargs.get('password'), "sha256")

    @classmethod
    def authenticated(cls, login, password):
        user = cls.query.filter(cls.login == login).one()
        if not check_password_hash(user.password, password):
            raise Exception('User not found')
        return user


@manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class Data(db.Model):
    __tablename__ = 'data'
    id = db.Column(db.Integer, primary_key=True)
    kind = db.Column(db.String(255), nullable=True)
    collection_name = db.Column(db.String(255), nullable=True)
    track_name = db.Column(db.String(255), nullable=True)
    collection_price = db.Column(db.Numeric(5, 2), nullable=True)
    track_price = db.Column(db.Numeric(7, 2), nullable=True)
    primary_genre_name = db.Column(db.String(255), nullable=True)
    track_count = db.Column(db.Numeric(10), nullable=True)
    track_number = db.Column(db.Numeric(10), nullable=True)
    release_date = db.Column(db.String(), nullable=True)

    def __init__(self, kind, collection_name, track_name, collection_price,\
                 track_price, primary_genre_name, track_count, track_number, release_date):
        self.kind = kind
        self.collection_name = collection_name
        self.track_name = track_name
        self.collection_price = collection_price
        self.track_price = track_price
        self.primary_genre_name = primary_genre_name
        self.track_count = track_count
        self.track_number = track_number
        self.release_date = release_date

application/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate


app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])

db = SQLAlchemy(app)
manager = LoginManager(app)
migrate = Migrate(app, db)

from application.models import *
from application.ui.views import ui

app.register_blueprint(ui)


if __name__ == '__main__':
    app.run()

application/ui/views.py
import os
import requests
from sqlalchemy import desc
from flask import render_template, redirect, url_for, request, flash, Blueprint
from flask_login import login_user, login_required, logout_user
from werkzeug.security import check_password_hash


from application import db
from application.models import User, Data


ui = Blueprint('ui', __name__)
VERSION = os.environ['VERSION']

def insert_data_from_api(search):
    total_count = 0
    record_count = 1
    record_offset = 0
    max_offset = 200
    while record_count > 0:
        response = (requests.get(
            'https://itunes.apple.com/search?term='+
            str(search)+
            '&offset='+
            str(record_offset)+
            '&limit='+
            str(max_offset-1))
        ).json()
        if response:
            record_count = response["resultCount"]
            total_count += record_count
            record_offset = int(record_offset) + max_offset
            dict_list = [
                'kind',
                'collectionName',
                'trackName',
                'collectionPrice',
                'trackPrice',
                'primaryGenreName',
                'trackCount',
                'trackNumber',
                'releaseDate'
            ]

            for record in response["results"]:
                session = db.session()
                out = []
                for element in dict_list:
                    data = record.get(element)
                    if not data:
                        out.append(None)
                        continue
                    out.append(data)

                row_data = Data(
                    kind=out[0],
                    collection_name=out[1],
                    track_name=out[2],
                    collection_price=out[3],
                    track_price=out[4],
                    primary_genre_name=out[5],
                    track_count=out[6],
                    track_number=out[7],
                    release_date=out[8],
                )
                session.add(row_data)
                session.commit()
                print(out)

        else:
            print('Response Failed')
    return total_count


def clean_database(data):
    num_rows_deleted = db.session.query(data).delete()
    db.session.commit()
    return num_rows_deleted


@ui.route('/')
def main():
    try:
        return render_template('index.html', ver=VERSION)
    except Exception as error_message:
        print(
            f'ip:{request.remote_addr} - \
            "GET / HTTP/1.1" 400 - \
            failed with errors: {error_message}')
        return {'Failed with errors': str(error_message)}, 400


@ui.route('/register', methods=['GET'])
def register():
    try:
        return render_template('register.html', ver=VERSION)
    except Exception as error_message:
        print(
            f'ip:{request.remote_addr} - \
            "GET /register HTTP/1.1" 400 - \
            failed with errors: {error_message}')
        return {'Failed with errors': str(error_message)}, 400


@ui.route('/register', methods=['POST'])
def register_post():
    login = request.form.get('login')
    password = request.form.get('password')
    password2 = request.form.get('password_retype')
    try:
        user = User.query.filter_by(login=login).first()

        if password != password2:
            flash('Password is not same')
            print(f'ip:{request.remote_addr}:user:{login} - \
                "POST /register HTTP/1.1" 200 - \
                Password is not same')
            return redirect(url_for('ui.register'))
        if user and login is not None:
            flash('User already exists')
            print(f'ip:{request.remote_addr}:user:{login} - \
                "POST /register HTTP/1.1" 200 - \
                user:{login} already exists')
            return redirect(url_for('ui.register'))

        if login and password and password2:
            new_user = User(login=login, password=password)
            db.session.add(new_user)
            db.session.commit()
            print(f'ip:{request.remote_addr}:user:{login} - \
                "POST /register HTTP/1.1" 200 - \
                Register successful')
            return redirect(url_for('ui.login_page'))
        flash('Fill in all the fields')
        print(f'ip:{request.remote_addr} - \
            "POST /register HTTP/1.1" 400 - \
            not all fields are filled in ')
        return redirect(url_for('ui.register')),400
    except Exception as error_message:
        print(
            f'ip:{request.remote_addr}:user:{login} - \
            "POST /api/register HTTP/1.1" 400 - \
            failed with errors: {error_message}')
        return {'Failed with errors': str(error_message)}, 400


@ui.route('/login', methods=['GET'])
def login_page():
    try:
        return render_template('login.html', ver=VERSION)
    except Exception as error_message:
        print(
            f'ip:{request.remote_addr} - \
            "GET /login HTTP/1.1" 400 - \
            failed with errors: {error_message}')
        return {'Failed with errors': str(error_message)}, 400


@ui.route('/login', methods=['POST'])
def login_page_post():
    try:
        login = request.form.get('login')
        password = request.form.get('password')
        if login and password:
            user = User.query.filter_by(login=login).first()

            if user and check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('ui.main'))
            flash('Wrong login or password')
        else:
            flash('Fill in all the fields')
        return redirect(url_for('ui.login_page'))
    except Exception as error_message:
        print(
            f'ip:{request.remote_addr}:user:{login} - \
            "POST /login HTTP/1.1" 400 - \
            failed with errors: {error_message}')
        return {'Failed with errors': str(error_message)}, 400


@ui.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    try:
        logout_user()
        return redirect(url_for('ui.main'))
    except Exception as error_message:
        print(
            f'ip:{request.remote_addr} - \
            "{request.method} /logout HTTP/1.1" 400 - \
            failed with errors: {error_message}')
        return {'Failed with errors': str(error_message)}, 400


@ui.route('/update', methods=['GET', 'POST'])
@login_required
def update():
    try:
        if request.method == 'POST':
            clean_count = clean_database(Data)
            print("Count clean: "+str(clean_count))
            total_count = insert_data_from_api('Pink+Floyd')
            flash('Total uploaded: '+str(total_count))
            return render_template('update.html', ver=VERSION)
        return render_template('update.html', ver=VERSION)

    except Exception as error_message:
        print(
            f'ip:{request.remote_addr} - \
            "GET /update HTTP/1.1" 400 - \
            failed with errors: {error_message}')
        return {'Failed with errors': str(error_message)}, 400


@ui.route('/get_data_all', methods=['GET'])
@login_required
def get_data():
    try:
        session = db.session()
        data_all = session.query(Data).order_by(desc("track_price")).all()
        return render_template('all_data.html', data_all=data_all, ver=VERSION)
    except Exception as error_message:
        print(
            f'ip:{request.remote_addr} - \
            "GET /update HTTP/1.1" 400 - \
            failed with errors: {error_message}')
        return {'Failed with errors': str(error_message)}, 400


@ui.route('/get_sort_data', methods=['GET', 'POST'])
@login_required
def get_sort_data():
    try:
        if request.method == 'POST':
            year = request.form.get('release_year')
            session = db.session()
            data_all = session.query(Data).order_by(desc("track_price")).all()
            result = []
            count = 0
            for data in data_all:
                if str(year) in str(data.release_date):
                    result.append(data)
                    count += 1
            flash("Find results: "+str(count))
            return render_template('sort_data.html', data_all=result, ver=VERSION)
        return render_template('sort_data.html', ver=VERSION)
    except Exception as error_message:
        print(
            f'ip:{request.remote_addr} - \
            "GET /get_sort_data HTTP/1.1" 400 - \
            failed with errors: {error_message}')
        return {'Failed with errors': str(error_message)}, 400

application/templates/all_data.html
{% extends "template.html" %}

{% block content %}
<div class="container">
    {% if data_all %}
    <div class="box">
        <table class="table table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
            <thead>
                <th>KIND</th>
                <th>COLLECTION NAME</th>
                <th>TRACK NAME</th>
                <th>COLLECTION PRICE</th>
                <th>TRACK PRICE</th>
                <th>PRIMARY GENRE NAME</th>
                <th>TRACK COUNT</th>
                <th>TRACK NUMBER</th>
                <th>RELEASE DATA</th>
            </thead>
            <tbody>
                {% for data in data_all %}
                <tr>
                    <td>{{ data.kind }}</td>
                        <td>{{ data.collection_name }}</td>
                        <td>{{ data.track_name }}</td>
                        <td>{{ data.collection_price }}</td>
                        <td>{{ data.track_price }}</td>
                        <td>{{ data.primary_genre_name }}</td>
                        <td>{{ data.track_count }}</td>
                        <td>{{ data.track_number }}</td>
                        <td>{{ data.release_date }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
</div>

{% endblock %}

application/templates/index.html
{% extends "template.html" %}
{% block content %}
        <div class="container has-text-centered">
        {% if current_user.is_authenticated %}
            <h1 class="title">
                Logged as: {{ current_user.login }}!
            </h1>
        {% else %}
            <h1 class="title">
              You are not authorized!
            </h1>
        {% endif %}
    </div>
{% endblock %}

application/templates/login.html
{% extends "template.html" %}
{% block content %}
    <div class="container has-text-centered">
        <div class="column is-4 is-offset-4">
            <h3 class="title">Login</h3>
            <div class="box">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="notification is-danger">
                            {{ messages[0] }}
                        </div>
                    {% endif %}
                {% endwith %}
                <form method="post">
                        <div class="field">
                            <div class="control">
                            <input class="input is-large" type="text" name="login" required placeholder="Username" autofocus="">
                            </div>
                        </div>

                        <div class="field">
                            <div class="control">
                            <input class="input is-large" type="password" name="password" required placeholder="Password">
                            </div>
                        </div>
                        <input class="button is-block is-info is-large is-fullwidth" type="submit" value="Sign in">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

application/templates/register.html
{% extends "template.html" %}
{% block content %}
    <div class="container has-text-centered">
        <div class="column is-4 is-offset-4">
            <h3 class="title">Create new account</h3>
            <div class="box">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="notification is-danger">
                            {% if messages[0] == "Пользователь уже существует" %}
                                {{ messages[0] }} <br>
                                Перейдите на страницу <a href="{{ url_for('ui.login_page') }}">Авторизации</a>
                            {% else %}
                                {{ messages[0] }}
                            {% endif %}
                        </div>
                    {% endif %}
                {% endwith %}

                <form method="post">
                    <div class="field">
                        <div class="control">
                            <input class="input is-large"  type="text" name="login" placeholder="Username" autofocus="">
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <input class="input is-large" type="password" name="password" required placeholder="Password">
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <input class="input is-large" type="password" name="password_retype" required placeholder="Retype password">
                        </div>
                    </div>

                    <input  class="button is-block is-info is-large is-fullwidth"  type="submit" value="Register">

                    <div class="field">
                        <div class="control">
                            If you already have an account, just <a href="{{ url_for('ui.login_page') }}">Sign in</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

application/templates/sort_data.html
{% extends "template.html" %}

{% block content %}
<div class="container">
    <div class="container">
        <div class ="control">
            <div class="container has-text-centered">
                <div class="column is-4 is-offset-4">
                    <div class="box">
                        <h3 class="title is-4">Filter</h3>
                        {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                <div class="notification is-success">
                                    {{ messages[0] }}
                                </div>
                            {% endif %}
                        {% endwith %}
                        <form action="" method="POST">
                            <div class="field has-addons">
                                <div class="control is-expanded">
                                    <input class="input"  type="text" name="release_year" placeholder="Year of release" autofocus="">
                                </div>
                                <div class="control">
                                    <button type="submit" class="button is-info " id="btnFiltr">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if data_all %}
    <div class="container">
        <div class="control">
            <div class="box">
                <table class="table table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                    <thead>
                        <th>KIND</th>
                        <th>COLLECTION NAME</th>
                        <th>TRACK NAME</th>
                        <th>COLLECTION PRICE</th>
                        <th>TRACK PRICE</th>
                        <th>PRIMARY GENRE NAME</th>
                        <th>TRACK COUNT</th>
                        <th>TRACK NUMBER</th>
                        <th>RELEASE DATA</th>
                    </thead>
                    <tbody>
                        {% for data in data_all %}
                        <tr>
                            <td>{{ data.kind }}</td>
                            <td>{{ data.collection_name }}</td>
                            <td>{{ data.track_name }}</td>
                            <td>{{ data.collection_price }}</td>
                            <td>{{ data.track_price }}</td>
                            <td>{{ data.primary_genre_name }}</td>
                            <td>{{ data.track_count }}</td>
                            <td>{{ data.track_number }}</td>
                            <td>{{ data.release_date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

application/templates/template.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EPAM Diploma</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <style>
        .loader {
          border: 5px solid #f3f3f3; /* Light grey */
          border-top: 5px solid #3498db; /* Blue */
          border-radius: 50%;
          width: 30px;
          height: 30px;
          animation: spin 2s linear infinite;
          margin: auto;
        }

        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
    </style>
</head>
<body>
<section class="hero is-fullheight" style="background-color:#e8e8e8;">
    <div class="hero-head">
        <nav class="navbar" style="background-color:#d0cdcd;">
            <div class="box" style="padding: 5px 5px; margin: auto 10px;">{{ ver }} </div>
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <a href="{{ url_for('ui.main') }}" class="navbar-item">
                            Home
                        </a>
                        {% if current_user.is_authenticated %}
                            <a href="{{ url_for('ui.update') }}" class="navbar-item">
                                Update data
                            </a>
                            <a href="{{ url_for('ui.get_sort_data') }}" class="navbar-item">
                                Sorting
                            </a>
                            <a href="{{ url_for('ui.get_data') }}" class="navbar-item">
                                All data
                            </a>
                        {% endif %}

                        {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('ui.login_page') }}" class="navbar-item">
                                Sign in
                            </a>
                            <a href="{{ url_for('ui.register') }}" class="navbar-item">
                                Register
                            </a>
                        {% endif %}
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('ui.logout') }}" class="navbar-item">
                            Log out
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="hero-body">
        {% block content %}{% endblock %}
    </div>
</section>
</body>
<script type="text/javascript">
$(document).ready(function() {
    $("#btnFetch").click(function() {
      // disable button
      $(this).prop("disabled", true);
      // add spinner to button
      $(this).html(
        `<span class="loader" aria-hidden="true"></span>`
      );
      $("#update-data").submit();
    });
});
</script>
</html>

application/templates/update.html
{% extends "template.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <div class="box">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-success">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}
        <form id ="update-data" class = "" action="" method="POST">
            <button type="submit" id="btnFetch" class="button is-block is-info is-large is-fullwidth">Update data in database</button>
        </form>
    </div>
</div>
{% endblock %}